import mongoose, { Schema } from 'mongoose';

const houseSchema = new mongoose.Schema(
  [
    {
      dataBasic: {
        typeUnit: { type: String, trim: true, required: true },
        typeOperation: { type: String, trim: true, required: true },
        price: { type: Number, trim: true, required: true },
        typePrice: { type: String, trim: true, required: true },
        state: { type: String, trim: true, required: true },
        credit: { type: Boolean, trim: true, required: true },
        barter: { type: Boolean, trim: true, required: true },
        title: { type: String, trim: true, required: true },
        commission: { type: String, trim: true, required: true },
      },
      surface: {
        covered: { type: Number, trim: true, required: true },
        semiCovered: { type: Number, trim: true, required: true },
        discovered: { type: Number, trim: true, required: true },
        total: { type: Number, trim: true, required: true },
      },
      location: {
        country: { type: String, trim: true, required: true },
        state: { type: String, trim: true, required: true },
        town: { type: String, trim: true, required: true },
        locality: { type: String, trim: true, required: true },
        nameStreet: { type: String, trim: true, required: true },
        numberStreet: { type: Number, trim: true, required: true },
        flat: { type: Number, trim: true, required: true },
        department: { type: Number, trim: true, required: true },
        postalCode: { type: String, trim: true, required: true },
        exactLocation: { type: String, trim: true, required: true }
      },
      mainFeatures: {
        hasBedrooms: { type: Boolean, trim: true, required: true },
        bedroomsAmount: { type: Number, trim: true, required: true },
        bedroomsSize: { type: Number, trim: true, required: true },
        hasBathrooms: { type: Boolean, trim: true, required: true },
        bathroomAmounty: { type: Number, trim: true, required: true },
        bathroomsSize: { type: Number, trim: true, required: true },
        hasToilettes: { type: Boolean, trim: true, required: true },
        toilettesAmount: { type: Number, trim: true, required: true },
        toilettesSize: { type: Number, trim: true, required: true },
        hasSuiteBathrooms: { type: Boolean, trim: true, required: true },
        suiteBathroomsAmount: { type: Number, trim: true, required: true },
        suiteBathroomsSize: { type: Number, trim: true, required: true },
        environmentsAmount: { type: Number, trim: true, required: true },
        hasKitchen: { type: Boolean, trim: true, required: true },
        kitchenSize: { type: Number, trim: true, required: true },
        hasIntegratedKitchen: { type: Boolean, trim: true, required: true },
        sizeKitchenIntegrated: { type: Number, trim: true, required: true },
        hasDinningRoom: { type: Boolean, trim: true, required: true },
        dinningRoomSize: { type: Number, trim: true, required: true },
        hasDailyDinningRoom: { type: Boolean, trim: true, required: true },
        dailyDinningRoomSize: { type: Number, trim: true, required: true },
        hasLivingRoom: { type: Boolean, trim: true, required: true },
        livingRoomSize: { type: Number, trim: true, required: true },
        hasLaundryRoom: { type: Boolean, trim: true, required: true },
        laundryRoomSize: { type: Number, trim: true, required: true },
        hasYard: { type: Boolean, trim: true, required: true },
        yardSize: { type: Number, trim: true, required: true },
        hasHall: { type: Boolean, trim: true, required: true },
        hallSize: { type: Number, trim: true, required: true },
        hasDesktop: { type: Boolean, trim: true, required: true },
        desktopSize: { type: Number, trim: true, required: true },
        hasPlayroom: { type: Boolean, trim: true, required: true },
        playroomSize: { type: Number, trim: true, required: true },
        hasTerrace: { type: Boolean, trim: true, required: true },
        terraceSize: { type: Number, trim: true, required: true },
        hasBarbecue: { type: Boolean, trim: true, required: true },
        barbecueSize: { type: Number, trim: true, required: true },
        hasPool: { type: Boolean, trim: true, required: true },
        poolSize: { type: Number, trim: true, required: true },
        hasServiceDependency: { type: Boolean, trim: true, required: true },
        serviceDependencySize: { type: Number, trim: true, required: true },
        hasFloors: { type: Boolean, trim: true, required: true },
        floorsQuantity: { type: Number, trim: true, required: true },
        hasGarages: { type: Boolean, trim: true, required: true },
        garagesQuantity: { type: Number, trim: true, required: true },
        garagesCover: { type: Number, trim: true, required: true },
        antiquity: { type: String, trim: true, required: true },
        antiquityYears: { type: Number, trim: true, required: true },
      },
      generalFeatures: {
        frontSize: { type: Number, trim: true, required: true },
        backSize: { type: Number, trim: true, required: true },
        insideFlooringType: { type: String, trim: true, required: true },
        woodFlooringType: { type: String, trim: true, required: true },
        outsideFlooringType: { type: String, trim: true, required: true },
        outsideWallsType: { type: String, trim: true, required: true },
        ceilingType: { type: String, trim: true, required: true },
        estateState: { type: String, trim: true, required: true },
        orientation: { type: String, trim: true, required: true },
        viewType: { type: String, trim: true, required: true },
        coastType: { type: String, trim: true, required: true },
        slopeType: { type: String, trim: true, required: true },
      },
      otherEnvironments: {
        loft: { type: Boolean, trim: true, required: true },
        beforeKitchen: { type: Boolean, trim: true, required: true },
        beforeLiving: { type: Boolean, trim: true, required: true },
        rooftop: { type: Boolean, trim: true, required: true },
        balcony: { type: Boolean, trim: true, required: true },
        balconyTerraced: { type: Boolean, trim: true, required: true },
        bar: { type: Boolean, trim: true, required: true },
        trunk: { type: Boolean, trim: true, required: true },
        library: { type: Boolean, trim: true, required: true },
        cellar: { type: Boolean, trim: true, required: true },
        toolRoom: { type: Boolean, trim: true, required: true },
        ironingRoom: { type: Boolean, trim: true, required: true },
        betweenFloor: { type: Boolean, trim: true, required: true },
        study: { type: Boolean, trim: true, required: true },
        familyRoom: { type: Boolean, trim: true, required: true },
        gallery: { type: Boolean, trim: true, required: true },
        shed: { type: Boolean, trim: true, required: true },
        garage: { type: Boolean, trim: true, required: true },
        garden: { type: Boolean, trim: true, required: true },
        freeBackground: { type: Boolean, trim: true, required: true },
        local: { type: Boolean, trim: true, required: true },
        office: { type: Boolean, trim: true, required: true },
        palier: { type: Boolean, trim: true, required: true },
        grill: { type: Boolean, trim: true, required: true },
        livingRoom: { type: Boolean, trim: true, required: true },
        basement: { type: Boolean, trim: true, required: true },
        suiteRoom: { type: Boolean, trim: true, required: true },
        lobby: { type: Boolean, trim: true, required: true },
        dressingRoom: { type: Boolean, trim: true, required: true },
        lockerRoom: { type: Boolean, trim: true, required: true },
      },
      installations: {
        sewer: { type: Boolean, trim: true, required: true },
        airHot: { type: Boolean, trim: true, required: true },
        televisionCable: { type: Boolean, trim: true, required: true },
        heatingBalanced: { type: Boolean, trim: true, required: true },
        breakfastNook: { type: Boolean, trim: true, required: true },
        bottledGas: { type: Boolean, trim: true, required: true },
        underfloorHeating: { type: Boolean, trim: true, required: true },
        trunk: { type: Boolean, trim: true, required: true },
        pool: { type: Boolean, trim: true, required: true },
        individualRadiantFloor: { type: Boolean, trim: true, required: true },
        hotWater: { type: Boolean, trim: true, required: true },
        furnished: { type: Boolean, trim: true, required: true },
        safe: { type: Boolean, trim: true, required: true },
        waterHeater: { type: Boolean, trim: true, required: true },
        electricity: { type: Boolean, trim: true, required: true },
        naturalGas: { type: Boolean, trim: true, required: true },
        kitchenFurniture: { type: Boolean, trim: true, required: true },
        radiators: { type: Boolean, trim: true, required: true },
        centralRadiantFloor: { type: Boolean, trim: true, required: true },
        centralAirConditioner: { type: Boolean, trim: true, required: true },
        individualAirConditioning: { type: Boolean, trim: true, required: true },
        kitchenGadgets: { type: Boolean, trim: true, required: true },
        singleBoiler: { type: Boolean, trim: true, required: true },
        soccerField: { type: Boolean, trim: true, required: true },
        tennisCourt: { type: Boolean, trim: true, required: true },
        vehicleSpace: { type: Boolean, trim: true, required: true },
        whirlpool: { type: Boolean, trim: true, required: true },
        reducedMobilityAccess: { type: Boolean, trim: true, required: true },
        elevator: { type: Boolean, trim: true, required: true },
        Heating: { type: Boolean, trim: true, required: true },
        airExtractor: { type: Boolean, trim: true, required: true },
        fireplace: { type: Boolean, trim: true, required: true },
        pavement: { type: Boolean, trim: true, required: true },
        waterHeater: { type: Boolean, trim: true, required: true },
        sprinklerIrrigation: { type: Boolean, trim: true, required: true },
      },
      services: {
        councilTax: { type: Boolean, trim: true, required: true },
        electricity: { type: Boolean, trim: true, required: true },
        cleaning: { type: Boolean, trim: true, required: true },
        security: { type: Boolean, trim: true, required: true },
        vigilance: { type: Boolean, trim: true, required: true },
        runningWater: { type: Boolean, trim: true, required: true },
        bottledGas: { type: Boolean, trim: true, required: true },
        refrigeration: { type: Boolean, trim: true, required: true },
        telephone: { type: Boolean, trim: true, required: true },
        heating: { type: Boolean, trim: true, required: true },
        naturalGas: { type: Boolean, trim: true, required: true },
        realEstateTax: { type: Boolean, trim: true, required: true },
        towels: { type: Boolean, trim: true, required: true },
        conmutador: { type: Boolean, trim: true, required: true },
        internet: { type: Boolean, trim: true, required: true },
        linen: { type: Boolean, trim: true, required: true },
        videoCable: { type: Boolean, trim: true, required: true },
      },
      multimedia: {
        frontPage: { type: String, trim: true, required: true },
        photoTour360: { type: String, trim: true, required: true },
        photo360: {
          photo: { type: String, trim: true, required: false },
          photo: { type: String, trim: true, required: false },
          photo: { type: String, trim: true, required: false },
          photo: { type: String, trim: true, required: false },
          photo: { type: String, trim: true, required: false },
          photo: { type: String, trim: true, required: false },
          photo: { type: String, trim: true, required: false },
          photo: { type: String, trim: true, required: false },
          photo: { type: String, trim: true, required: false },
          photo: { type: String, trim: true, required: false },
          photo: { type: String, trim: true, required: false },
          photo: { type: String, trim: true, required: false },
          photo: { type: String, trim: true, required: false },
          photo: { type: String, trim: true, required: false },
          photo: { type: String, trim: true, required: false },
          photo: { type: String, trim: true, required: false },
        },
      },
      additionalInformation: {
        description: { type: String, trim: true, required: true },
        notes: { type: String, trim: true, required: false },
      },
      contactOwner: {
        email: { type: String, trim: true, required: true },
        telephone: { type: Number, trim: true, required: true },
        mobile: { type: Number, trim: true, required: true },
        alternativeTelephone: { type: Number, trim: true, required: true },
        whatsApp: { type: Number, trim: true, required: true },
      },
      statistics: {
        views: { type: Number, trim: true, required: false },
        queries: { type: Number, trim: true, required: false },
        viewsTour: { type: Number, trim: true, required: false },
        interested: { type: Number, trim: true, required: false },
        offered: { type: Number, trim: true, required: false },
        reserved: { type: Number, trim: true, required: false },
        likes: { type: Number, trim: true, required: false },
      },
    },
  ],
  {
    timestamps: true,
  }
);

const House = mongoose.model('houses', houseSchema);
export default House;
