export const dataBasic = {
    unit: '',
    operation: '',
    price: null,
    dontShowPrice: false,
    currency: '',
    state: '',
    suitableCredit: false,
    acceptsExchange: false,
    suitableProfesional: false,
    propertyOccupied: false,
    suitablePets: false,
    title: '',
    commission: null
};

export const dataEntrepreneurship = {
    state: '',
    maximumDateYear: '',
    maximumDateMonth: '',
    bedroomsQuantity: null,
    insideCountry: false,
};

export const dataCountry = {
    name: false,
    zone: false,
    state: false,
    urbanization: false,
    basketball: false,
    horseRiding: false,
    football: false,
    golf: false,
    hockey: false,
    paddle: false,
    polo: false,
    rugby: false,
    tennis: false,
    volleyball: false,
    clubHouse: false,
    gym: false,
    games: false,
    laundry: false,
    pool: false,
    multipurposeRoom: false,
    stable: false,
    school: false,
    bank: false,
    mall: false
};

export const surface = {
    covered: null,
    semiCovered: null,
    discovered: null,
    total: null,
};

export const location = {
    country: 'Argentina',
    province: '',
    state: '',
    locality: '',
    streetName: '',
    streetNumber: '',
    flat: 0,
    department: '',
    postalCode: 0,
    locationType: ''
};

export const mainFeatures = {
    hasBedrooms: false,
    bedroomsQuantity: 1,
    bedroomsSize: '',
    hasBathrooms: false,
    bathroomsQuantity: 1,
    bathroomsSize: '',
    hasToilettes: false,
    toilettesQuantity: 1,
    toilettesSize: '',
    hasSuiteBathrooms: false,
    suiteBathroomsQuantity: 1,
    suiteBathroomsSize: '',
    environmentsQuantity: 1,
    setup: '',
    columnsQuantity: 1,
    shedsQuantity: 1,
    roomsQuantity: 1,
    starsQuantity: 1,
    placesQuantity: 1,
    roomsPerFloor: 1,
    staffQuantity: 1,
    hasKitchen: false,
    kitchenSize: '',
    hasIntegratedKitchen: false,
    integratedKitchenSize: '',
    hasDinningRoom: false,
    dinningRoomSize: '',
    hasDailyDinningRoom: false,
    dailyDinningRoomSize: '',
    hasLivingRoom: false,
    livingRoomSize: '',
    hasLaundryRoom: false,
    laundryRoomSize: '',
    hasYard: false,
    yardSize: '',
    hasHall: false,
    hallSize: '',
    hasDesktop: false,
    desktopSize: '',
    hasPlayroom: false,
    playroomSize: '',
    hasTerrace: false,
    terraceSize: '',
    hasBarbecue: false,
    barbecueSize: '',
    hasPool: false,
    poolSize: '',
    hasServiceDependency: false,
    serviceDependencySize: '',
    hasFloors: false,
    floorsQuantity: 1,
    hasBalcony: false,
    balconyType: '',
    balconySize: '',
    hasGarages: false,
    garagesQuantity: 1,
    garagesType: '',
    garagesCover: '',
    carType: '',
    accessType: '',
    length: null,
    width: null,
    height: null,
    antiquity: '',
    antiquityYears: null,
    pavementDistance: null,
    hectaresQuantity: null
};

export const generalFeatures = {
    frontSize: '',
    backSize: '',
    fullLoadFactor: null,
    landCoverFactor: null,
    linealRightMeasure: '',
    linealLeftMeasure: '',
    zoning: '',
    insideFlooring: '',
    woodFlooring: '',
    outsideFlooring: '',
    outsideWalls: '',
    ceiling: '',
    estateState: '',
    orientation: '',
    view: '',
    coast: '',
    slope: '',
    cornerDistance: null,
    monthlyIncome: '',
    yearlyIncome: '',
    cutleryQuantity: null,
};

export const otherEnvironments = {
    loft: false,
    beforeKitchen: false,
    file: false,
    beforeLiving: false,
    rooftop: false,
    balcony: false,
    balconyTerraced: false,
    bar: false,
    trunk: false,
    library: false,
    cellar: false,
    circulation: false,
    toolRoom: false,
    ironingRoom: false,
    warehouse: false,
    betweenFloor: false,
    studio: false,
    familyRoom: false,
    gallery: false,
    shed: false,
    garage: false,
    garden: false,
    freeBackground: false,
    shop: false,
    office: false,
    palier: false,
    grill: false,
    livingRoom: false,
    meetingRoom: false,
    workRoom: false,
    lounge: false,
    publicHall: false,
    basement: false,
    suite: false,
    lobby: false,
    dressingRoom: false,
    lockerRoom: false,
};

export const installations = {
    sewerWater: false,
    hotAir: false,
    televisionCable: false,
    heatingBalanced: false,
    breakfastNook: false,
    bottledGas: false,
    underfloorHeating: false,
    pool: false,
    individualRadiantFloor: false,
    hotWater: false,
    furnished: false,
    safe: false,
    waterHeater: false,
    electricity: false,
    naturalGas: false,
    kitchenFurniture: false,
    radiators: false,
    centralRadiantFloor: false,
    centralAirConditioner: false,
    individualAirConditioner: false,
    kitchenGadgets: false,
    singleBoiler: false,
    soccerField: false,
    tennisCourt: false,
    vehicleSpace: false,
    whirlpool: false,
    reducedMobilityAccess: false,
    solarium: false,
    elevator: false,
    heating: false,
    airExtractor: false,
    fireplace: false,
    pavement: false,
    hotWaterTank: false,
    sprinklerIrrigation: false,
    gym: false,
    generator: false,
    gamesForKids: false,
    laundry: false,
    underfloorDucts: false,
    partyRoom: false,
    sauna: false,
    telephone: false,
    commutator: false,
    window: false,
    runningWater: false,
    weightScale: false,
    pumper: false,
    drivingForce: false,
    industrialGas: false,
    crane: false,
    liftTruck: false,
    motors: false,
    gate: false,
    waterTank: false,
    fireTank: false,
    boxes: false,
    electricLight: false,
    wellWater: false,
    waterSources: false,
    grove: false,
    drinker: false,
    straps: false,
    barnyard: false,
    fence: false,
    afforestation: false,
    pits: false,
    horseFarm: false,
    reducedFence: false,
    windmill: false,
    livingPlace: false,
    sewageTreatment: false,
    wireFences: false,
    basketballCourt: false,
    volleyballCourt: false,
    hockeyCamp: false,
    squashCourt: false,
    paddleCourt: false,
    paddock: false,
    creamery: false,
    restaurant: false,
};

export const services = {
    councilTax: false,
    electricity: false,
    cleaning: false,
    security: false,
    vigilance: false,
    runningWater: false,
    bottledGas: false,
    refrigeration: false,
    telephone: false,
    heating: false,
    naturalGas: false,
    realEstateTax: false,
    towels: false,
    commutator: false,
    internet: false,
    linen: false,
    videoCable: false,
    laundry: false,
    cooking: false,
    bar: false,
};

export const building = {
    mainFeatures: {
        floorsQuantity: 1,
        flatsPerFloor: 1,
        garagesQuantity: 1,
        buildingType: '',
        antiquity: '',
        antiquityYears: null,
        hasElevator: false,
        elevatorType: '',
        estateState: '',
        outsideWalls: '',
        view: '',
        coast: '',
    },
    installations: {
        multipurposeRoom: false,
        pool: false,
        centralAirConditioner: false,
        individualAirConditioner: false,
        boiler: false,
        soccerField: false,
        tennisCourt: false,
        vehicleSpace: false,
        whirlpool: false,
        reducedMobilityAccess: false,
        solarium: false,
        elevator: false,
        heating: false,
        airExtractor: false,
        barbecue: false,
        park: false,
        sprinklerIrrigation: false,
        surveillanceCameras: false,
        terrace: false,
    },
    services: {
        doorkeeper: false,
        councilTax: false,
        electricity: false,
        cleaning: false,
        security: false,
        vigilance: false,
        runningWater: false,
        bottledGas: false,
        refrigeration: false,
        telephone: false,
        heating: false,
        naturalGas: false,
        laundry: false,
        commutator: false,
        internet: false,
        linen: false,
        videoCable: false,
    }
};

export const multimedia = {
    frontPage: "/",
    photoTour360: "/",
    photo360: {
      photo1: "/",
      photo2: "/",
      photo3: "/",
      photo4: "/",
      photo5: "/",
      photo6: "/",
      photo7: "/",
      photo8: "/",
      photo9: "/",
      photo10: "/",
      photo11: "/",
      photo12: "/",
      photo13: "/",
      photo14: "/",
      photo15: "/",
      photo16: "/",
    },
};

export const addiotinalInformation = {
    description: '',
    notes: ''
};

export const contactOwner = {
    email: '',
    telephone: '',
    mobile: '',
    alternativeTelephone: '',
    whatsApp: ''
};